//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBApiFinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_Id{ get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Joing_Date { get; set; }
        public string Department { get; set; }
    }
}
