//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCrudApplication.Models
{
    using System;
    using System.Collections.Generic;
  

    public partial class UserReg
    {
        public int Userid { get; set; }
        public string UserType { get; set; }
        public string UserName { get; set; }
        public string UserEmailid { get; set; }
        public string Password { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string UserProfileImage { get; set; }

        public static string[] getCountry()
        {
            return new string[] { "India", "Australia", "America" };
        }

        public static string[] getUserType()
        {
            return new string[] { "Admin", "Employee", "User" };
        }
    }
}
